name: Generate Docs

on:
  pull-request:
    branches: [master]

jobs:
  serve-api-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.head_ref}}
      - name: Build API docs
        run: |
          ./vendor/bin/openapi --format yaml --output ./swagger/swagger.yaml ./swagger/swagger.php src
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update api docs
